### Pandas + NumPy Data Cleaning

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\customer_data - customer_data.csv")

In [5]:
1.
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

In [6]:
2.
df.shape

(2000, 15)

In [8]:
3.
df.columns

Index(['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [9]:
4.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       1980 non-null   object
 1   Age               1669 non-null   object
 2   income_usd        1560 non-null   object
 3   credit Score      1640 non-null   object
 4   tenure_years      1742 non-null   float64
 5   monthly_visits    1720 non-null   float64
 6   satisfaction      1601 non-null   float64
 7   City              1700 non-null   object
 8   customer_segment  1620 non-null   object
 9   gender            1760 non-null   object
 10  is_active         1660 non-null   object
 11  churn_flag        1840 non-null   object
 12  signup_date       1760 non-null   object
 13  lead_source       1580 non-null   object
 14  notes_text        1344 non-null   object
dtypes: float64(3), object(12)
memory usage: 234.5+ KB

In [10]:
5.
df['missing_values']=df.isnull().sum()/len(df) * 100
df['missing_values']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1995   NaN
1996   NaN
1997   NaN
1998   NaN
1999   NaN
Name: missing_values, Length: 2000, dtype: float64

In [11]:
6.
missing_id = df['Customer ID'].isna().sum()
print(missing_id)

20

In [12]:
7.
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
print(df.columns)

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text',
       'missing_values'],
      dtype='object')

In [13]:
8.
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [14]:
9.
df.drop_duplicates()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,missing_values
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed,NaN
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal,NaN
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal,NaN
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good,NaN
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???,NaN
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok,NaN
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good,NaN

In [15]:
10.
df['customer_segment'].unique()

array(['consumer', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [16]:
11.
df['customer_segment'] = (
    df['customer_segment']
    .astype(str)
    .str.strip()
    .str.lower()
    .str.title()
)

print("\nUnique values after cleaning:")
print(df['customer_segment'].unique())

Unique values after cleaning:
['Consumer' 'Enterprise' 'Smb' 'Nan' 'Smb.' 'Unknown']

In [18]:
12.
print(df['gender'].unique())

df['gender'] = df['gender'].astype(str).str.strip().str.lower()

df['gender'] = df['gender'].replace({
        'm': 'Male',
        'male': 'Male',
        'f': 'Female',
        'female': 'Female'
    })

print(df['gender'].unique())

[nan 'Male' 'm' 'Female' 'M' 'F' 'f']
['nan' 'Male' 'Female']

In [19]:
13.
print(df['is_active'].unique())

df['is_active'] = (
    df["is_active"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'yes': 1,
        'y': 1,
        '1': 1,
        'no': 0,
        'n': 0,
        '0': 0
    })
)

print(df['is_active'].unique())

['Yes' nan 'N' 'yes' 'No' 'no' 'Y' '1' '0']
[1 'nan' 0]

In [20]:
14.
df['churn_flag'] = df['churn_flag'].map({'Yes' : 1, 'No' : 0})
df.head(10)

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text,missing_values
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,Consumer,nan,1,0.0,2026-03-11,Referral,NaN,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,nan,0.0,NaN,website,follow-up needed,NaN
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,Male,1,0.0,2024-09-20,Email,NaN,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,Male,0,0.0,2023-07-12,Website,normal,NaN
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,1,0.0,2024-08-06,NaN,???,NaN
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,Smb,Male,1,1.0,21/07/2024,NaN,follow-up needed,NaN
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,nan,1,1.0,2023-08-14,google_ads,NaN,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,Nan,Female,0,0.0,NaN,NaN,good customer,NaN
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,Smb.,Male,0,NaN,2021-03-08,Social,NaN,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,Male,0,0.0,2024-09-10,Website,normal,NaN

In [24]:
15.
invalid_income = df[
    pd.to_numeric(df["income_usd"],errors="coerce").isna()
    & df["income_usd"].notna()
]["income_usd"]
print(invalid_income.unique())

['$44,696' '$41,941' '$123,682' '$40,978' '$45,565' '$112,864' '$38,946'
 '$93,738' '$70,056' '$26,771' 'missing' '$48,959' '$36,410' '$86,520'
 '$88,847' '$88,960' '$50,211' '$104,630' '$72,142' '$34,864' '$130,837'
 '$90,730' '$29,657' '$60,407' '₹55k' '$506,709' '$71,214' '$191,997'
 '$35,341' '$171,139' '$65,761' '$30,152' '$47,631' '$319,924' '$46,216'
 '$49,366' '$78,703' '$44,955' '$76,860' '$50,094' '$129,799' '$32,702'
 '$33,399' '$19,760' '$146,497' '$30,746' '$107,324' '$19,808' 'error'
 '$49,885' '$22,575' '$53,462' '$100,254' '$37,397' '$89,920' '$60,643'
 '$153,576' '$114,703' '$117,570' '$155,204' '$39,065' '$108,002'
 '$33,428' '$18,612' '$32,495' '$31,099' '$60,008' '$31,588' '$84,034'
 '$92,205' '$30,921' '$38,009' '$61,792' '$48,656' '$49,855' '$23,569'
 '$38,605' '$37,860' '$47,580' '$24,527' '$78,202' '$53,993' '$64,415'
 'not available' '$99,869' '$543,686' '$74,109' '$45,886' '$75,683'
 '$59,291' '$41,955' '$37,026' '$13,148' '$56,234' '$73,642' '$44,722'
 '$39,362' '$41,269' '$33,259' '$34,160' '$45,415' '$55,242' '$99,697'
 '$35,506' '$352,568' '$25,393' '$20,322' '$65,732' '$15,187' '$61,230'
 '$38,916' '$97,960' '$93,193' '$42,625' '$36,305' '$89,682' '$33,715'
 '$34,982' '$45,435' '$212,590' '$151,415' '$38,849' '$256,510' '$25,921'
 '$52,112' '$155,352' '$45,288' '$76,139' '$48,047' '$27,675' '$55,161'
 '$63,822' '$124,103' '$26,579' '$27,606' '$87,822' '$83,857' '$31,808'
 '$24,295' '$22,540' '$38,251' '$41,234' '$506,702' '$64,045' '$52,352'
 '$31,857' '$98,449' '$54,157' '$49,817' '$17,863' '$160,831' '$119,220'
 '$264,787' '$69,968' '$105,759' '$76,027' '$24,407' '$135,870' '$40,483'
 '$68,496' '$53,034' '$50,179' '$41,996' '$295,916' '$100,739' '$64,975'
 '$64,537' '$30,668' '$47,068' '$51,813' '$57,778' '$50,057' '$125,589'
 '$22,832' '$58,551' '$135,575' '$34,809' '$80,389' '$58,046']